### ISSUE TITLE
Build on Windows

### ISSUE THREAD

**Issue by webfolderio** [mpenick/uvtls#3]
Hi,

I am trying to build uvtls on Windows platform with [vcpkg](https://github.com/microsoft/vcpkg).

__http-client.exe__ works with google.com, amazon.com etc. but __test-uvtls.exe__ fails.

Patch: https://github.com/webfolderio/uvtls/commit/1261ae050d4d01487840ce5afa50f644eb6e9c49

OpenSSL version: 1.1.1d-1
libuv version: 1.34.2
MSVC Version: 2017 (x86)

Test result:
```
[==========] Running 13 tests from 2 test cases.
[----------] 8 tests from ring_buf
[ RUN      ] ring_buf.one_block
[       OK ] ring_buf.one_block (10 ms)
[ RUN      ] ring_buf.two_blocks
[       OK ] ring_buf.two_blocks (11 ms)
[ RUN      ] ring_buf.tail_commit
[       OK ] ring_buf.tail_commit (10 ms)
[ RUN      ] ring_buf.head_commit_one_block
[       OK ] ring_buf.head_commit_one_block (8 ms)
[ RUN      ] ring_buf.head_commit_one_block_partial_read
[       OK ] ring_buf.head_commit_one_block_partial_read (8 ms)
[ RUN      ] ring_buf.head_commit_two_blocks
[       OK ] ring_buf.head_commit_two_blocks (10 ms)
[ RUN      ] ring_buf.head_commit_two_blocks_read_to_next_block
[       OK ] ring_buf.head_commit_two_blocks_read_to_next_block (8 ms)
[ RUN      ] ring_buf.head_commit_two_blocks_partial_read
[       OK ] ring_buf.head_commit_two_blocks_partial_read (8 ms)
[----------] 8 tests from ring_buf (100 ms total)

[----------] 5 tests from client
[ RUN      ] client.connect
[       OK ] client.connect (28 ms)
[ RUN      ] client.verify_peer_cert
Assertion failed: req != current, file c:\tools\vcpkg\buildtrees\libuv\src\21008c5b8e-d2b85aa913\src\win\req-inl.h, line 99
[   FAILED ] client.verify_peer_cert (1638 ms)
[ RUN      ] client.verify_bad_peer_cert
Assertion failed: req != current, file c:\tools\vcpkg\buildtrees\libuv\src\21008c5b8e-d2b85aa913\src\win\req-inl.h, line 99
[   FAILED ] client.verify_bad_peer_cert (592 ms)
[ RUN      ] client.verify_peer_ident
Assertion failed: req != current, file c:\tools\vcpkg\buildtrees\libuv\src\21008c5b8e-d2b85aa913\src\win\req-inl.h, line 99
[   FAILED ] client.verify_peer_ident (530 ms)
[ RUN      ] client.verify_bad_peer_ident
Assertion failed: req != current, file c:\tools\vcpkg\buildtrees\libuv\src\21008c5b8e-d2b85aa913\src\win\req-inl.h, line 99
[   FAILED ] client.verify_bad_peer_ident (481 ms)
[----------] 5 tests from client (3315 ms total)

[==========] 13 tests ran from 2 test cases. (3424 ms total)
[  PASSED  ] 9 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] client.verify_peer_cert
[  FAILED  ] client.verify_bad_peer_cert
[  FAILED  ] client.verify_peer_ident
[  FAILED  ] client.verify_bad_peer_ident

test-uvtls.exe (process 7804) exited with code 1.
```

**Comment by webfolderio** [comment]
Similar bug: https://github.com/libuv/help/issues/122

**Comment by mpenick** [comment]
Hey, thanks. I've just started working on the Windows build (for CI). I'll take a look over the next couple days and let you know what I find.

**Comment by webfolderio** [comment]
Here is my patch to build uvtls on GitHub actions (Windows only). You could modify your build configuration based on this patch.

* Updated build configuration: [ccpp.yml](https://github.com/webfolderio/uvtls/blob/master/.github/workflows/ccpp.yml)
* Disable the crash popup and redirect assert messages to console: [main.c](https://github.com/webfolderio/uvtls/blob/master/tests/main.c). Build process hangs if error messages are not redirect to console. Libuv [test runner](https://github.com/libuv/libuv/blob/v1.x/test/runner-win.c#L45) uses similar method.

Sample build: https://github.com/webfolderio/uvtls/runs/452393205

**Comment by mpenick** [comment]
I've been able to reproduce the issue on my local machine. I'm working on a fix.

**Comment by mpenick** [comment]
Here's an issue I found: https://github.com/libuv/libuv/pull/2688.

**Comment by mpenick** [comment]
So I'm 99.9% sure this is a libuv issue. I have a small, reproducible example for the issue included in this PR: https://github.com/libuv/libuv/pull/2688

**Comment by mpenick** [comment]
@webfolderio Added a workaround https://github.com/mpenick/uvtls/commit/3edb2bb9e7ac03b6a79ed4aede99186b0aa0dc9b  and added Windows to the CI in this PR: https://github.com/mpenick/uvtls/pull/4

**Comment by mpenick** [comment]
Thanks for your contributions. That vcpkg caching is awesome!
